print("What's the length of the room?")
length=input()
print("What's the width of the room")
width=input()
area=int(length)*int(width)
print("the area of the room is:",area)
print("the area of the room is:",area*9)
print("What's the price of the carpet?",end="")
price=input()
print("the total price of the room is:",int(price)*int(area))
